-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."DimDate"
(
    dateid integer,
    date date,
    year integer,
    quarter integer,
    quartername character varying(50),
    month integer,
    monthname character varying(50),
    day integer,
    weekday integer,
    weekdayname character varying(50),
    PRIMARY KEY (dateid)
);

CREATE TABLE IF NOT EXISTS public."DimCategory"
(
    categoryid integer,
    category character varying(50),
    PRIMARY KEY (categoryid)
);

CREATE TABLE IF NOT EXISTS public."DimCountry"
(
    countryid integer,
    country character varying(50),
    PRIMARY KEY (countryid)
);

CREATE TABLE IF NOT EXISTS public."FactSales"
(
    orderid integer,
    dateid integer,
    countryid integer,
    categoryid integer,
    amount integer,
    PRIMARY KEY (orderid)
);

ALTER TABLE IF EXISTS public."FactSales"
    ADD CONSTRAINT fk_fact_date FOREIGN KEY (dateid)
    REFERENCES public."DimDate" (dateid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."FactSales"
    ADD CONSTRAINT fk_fact_category FOREIGN KEY (categoryid)
    REFERENCES public."DimCategory" (categoryid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."FactSales"
    ADD CONSTRAINT fk_fact_country FOREIGN KEY (countryid)
    REFERENCES public."DimCountry" (countryid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;

